{% set name = "strongtyping" %}
{% set version = "3.12.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/FelixTheC/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3e482909134afacda65ad2d1fddf8610c15faec62d9d40b75303bc8105131123

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.10,<4.0
  run:
    - python >=3.10,<4.0
    - ujson >=5.5.0,<6.0.0

test:
  imports:
    - strongtyping
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://strongtyping.readthedocs.io/en/latest/
  dev_url: https://github.com/FelixTheC/strongtyping
  summary: Decorator which checks whether the function is called with the correct type of parameters
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - thewchan
