{% set name = "strongtyping" %}
{% set version = "2.1.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/strongtyping-{{ version }}.tar.gz
  sha256: b99456d351c66c231a2f6bc114faf09181cc565422b876c4194b1641bfede940

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - mypy
    - python >=3.7

test:
  imports:
    - easy_property
    - strongtyping
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://strongtyping.readthedocs.io/en/latest/
  dev_url: https://github.com/FelixTheC/strongtyping
  summary: Decorator which checks whether the function is called with the correct type of parameters
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - thewchan
