{% set name = "strongtyping" %}
{% set version = "3.11.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/strongtyping-{{ version }}.tar.gz
  sha256: 9fb89efce062cce779eac7b2c35ea25e5364a12f75b02aa28794d01ad57b8a7e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - strongtyping
  # commands:
  # disabling pip check test because upstream pyproject.toml listed dev dependencies as run dependencies
#     - pip check
  requires:
    - pip

about:
  home: https://strongtyping.readthedocs.io/en/latest/
  dev_url: https://github.com/FelixTheC/strongtyping
  summary: Decorator which checks whether the function is called with the correct type of parameters
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - thewchan
