schema_version: 1

context:
  python_min: 3.13
  name: strongtyping
  version: 3.13.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/FelixTheC/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 174d330c9ecc311ff0b6111584a2b76c9c13cb5587d224be0adaded5b994b95a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - ujson >=5.5.0,<6.0.0

tests:
  - python:
      imports:
        - strongtyping
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Decorator which checks whether the function is called with the correct type of parameters
  license: MIT
  license_file: LICENSE.md
  homepage: https://strongtyping.readthedocs.io/en/latest/
  repository: https://github.com/FelixTheC/strongtyping

extra:
  recipe-maintainers:
    - thewchan
