schema_version: 1

context:
  python_min: 3.13
  name: strongtyping
  version: "3.13.5"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/FelixTheC/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: d075e2d446c94acdef6ea1015d8d5a9c55c09debc62f67af9039d17cc4fffa18

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=61.0
    - wheel
  run:
    - python >=${{ python_min }}
    - ujson 5.6.0.*

tests:
  - python:
      imports:
        - strongtyping
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Decorator which checks whether the function is called with the correct type of parameters
  license: MIT
  license_file: LICENSE.md
  homepage: https://strongtyping.readthedocs.io/en/latest/
  repository: https://github.com/FelixTheC/strongtyping

extra:
  recipe-maintainers:
    - thewchan
